# -*- coding: utf-8 -*-
"""1LifeScan_AI_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dxf5PEhVwXdN3WFf2MvllAFx8-Lg0EAZ

============================================================
        LifeScan AI System — Heart Disease Risk Predictor
        A Complete ML Pipeline for Binary Classification
        Dataset  : Heart Failure Prediction (heart.csv)
        Target   : HeartDisease  (0 = No Heart Disease,
                                  1 = Heart Disease Present)
        Platform : Google Colab  |  Language: Python 3
============================================================

 HOW TO USE THIS NOTEBOOK IN GOOGLE COLAB
 ------------------------------------------
 1. Upload heart.csv to your Colab session files
    (click the folder icon → upload button).
 2. Run every cell in order from top to bottom.
 3. Read every comment — they explain WHY, not just WHAT.

============================================================

██████████████████████████████████████████████████████████
 SECTION 1 ── IMPORT LIBRARIES
██████████████████████████████████████████████████████████

----------------------------------------------------------
Why import libraries?
Python alone cannot do statistics, plotting, or machine
learning.  We import specialised libraries that give us
pre-built, highly-optimised tools so we don't reinvent
the wheel.
----------------------------------------------------------
"""

# ── Standard library ──────────────────────────────────────
import warnings                      # suppress non-critical warnings
warnings.filterwarnings('ignore')    # keeps output clean

# ── Data manipulation ─────────────────────────────────────
import numpy as np                   # fast numerical arrays & math
import pandas as pd                  # tabular data (DataFrames)

# ── Visualisation ─────────────────────────────────────────
import matplotlib.pyplot as plt      # base plotting engine
import seaborn as sns                # high-level statistical plots

# ── Preprocessing ─────────────────────────────────────────
from sklearn.preprocessing import (
    LabelEncoder,    # converts text categories → integers
    StandardScaler   # rescales features to mean=0, std=1
)

# ── Data splitting ────────────────────────────────────────
from sklearn.model_selection import train_test_split   # hold-out split

# ── Machine Learning models ───────────────────────────────
from sklearn.linear_model import LogisticRegression    # baseline linear model
from sklearn.ensemble import RandomForestClassifier    # ensemble tree model
from sklearn.svm import SVC                            # kernel-based model

# ── Model evaluation metrics ─────────────────────────────
from sklearn.metrics import (
    accuracy_score,       # fraction of correct predictions
    precision_score,      # of predicted positives, how many are truly positive?
    recall_score,         # of actual positives, how many did we catch?
    f1_score,             # harmonic mean of precision & recall
    confusion_matrix,     # 2×2 table: TP, FP, FN, TN
    classification_report # full per-class metric summary
)

# ── Model persistence ─────────────────────────────────────
import joblib   # saves / loads trained models efficiently

# ── Operating system utilities ────────────────────────────
import os       # file path handling

print("✅  All libraries imported successfully.")
print(f"    NumPy   version : {np.__version__}")
print(f"    Pandas  version : {pd.__version__}")

"""██████████████████████████████████████████████████████████
 SECTION 2 ── LOAD DATASET
██████████████████████████████████████████████████████████

----------------------------------------------------------
heart.csv is the Heart Failure Prediction Dataset
originally published on Kaggle.  It combines patient
records from Cleveland, Hungary, Switzerland, Long Beach
VA, and Stalog datasets — 918 observations in total.

Column descriptions (brief):
  Age          – patient age in years
  Sex          – M / F
  ChestPainType– ATA, NAP, ASY, TA
  RestingBP    – resting blood pressure (mm Hg)
  Cholesterol  – serum cholesterol (mm/dl)
  FastingBS    – fasting blood sugar >120 mg/dl (1=True)
  RestingECG   – electrocardiogram result
  MaxHR        – maximum heart rate achieved
  ExerciseAngina – exercise-induced angina (Y/N)
  Oldpeak      – ST depression (numeric)
  ST_Slope     – slope of peak exercise ST segment
  HeartDisease – 1 = disease, 0 = no disease  ← TARGET
----------------------------------------------------------
"""

# Load the CSV file into a Pandas DataFrame
# Adjust the path if you have uploaded the file elsewhere.
df = pd.read_csv('heart.csv')

print("=" * 60)
print("  DATASET LOADED")
print("=" * 60)

# ── First five rows ───────────────────────────────────────
print("\n📋  First 5 rows of the dataset:")
print(df.head())

# ── Shape of the dataset ─────────────────────────────────
print(f"\n📐  Dataset shape : {df.shape[0]} rows  ×  {df.shape[1]} columns")

# ── Column names ─────────────────────────────────────────
print(f"\n🏷️   Column names  : {list(df.columns)}")

"""██████████████████████████████████████████████████████████
 SECTION 3 ── DATA UNDERSTANDING
██████████████████████████████████████████████████████████

----------------------------------------------------------
Before building any model we must understand:
  • Data types of every column
  • Statistical summary (mean, std, min, max, quartiles)
  • Whether the target classes are balanced or skewed
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  DATA UNDERSTANDING")
print("=" * 60)

# ── .info() ──────────────────────────────────────────────
# Shows column names, non-null counts, and dtypes.
# Helps detect hidden nulls that appear 0 but aren't.
print("\n🔍  DataFrame info:")
print(df.info())

# ── .describe() ──────────────────────────────────────────
# Shows mean, std, min, 25%, 50%, 75%, max for numeric cols.
# Outliers show up as extreme min/max values.
print("\n📊  Statistical summary (numeric columns):")
print(df.describe().round(2))

# ── Class distribution of target variable ────────────────
print("\n🎯  Target variable distribution — HeartDisease:")
class_counts = df['HeartDisease'].value_counts()
class_pct    = df['HeartDisease'].value_counts(normalize=True) * 100

for label, count in class_counts.items():
    tag = "Heart Disease" if label == 1 else "No Heart Disease"
    print(f"    Class {label} ({tag}): {count} samples  "
          f"({class_pct[label]:.1f}%)")

# ── Imbalance check and explanation ──────────────────────
ratio = class_counts[1] / class_counts[0]
if 0.8 <= ratio <= 1.25:
    print("\n  ✅  Classes are reasonably balanced — "
          "no resampling required.")
else:
    print(f"\n  ⚠️   Class imbalance detected (ratio ≈ {ratio:.2f}).")
    print("      In healthcare, missing a positive case (False Negative)")
    print("      is far more dangerous than a False Positive.")
    print("      Consider oversampling (SMOTE) or class_weight='balanced'.")

"""██████████████████████████████████████████████████████████
 SECTION 4 ── DATA CLEANING  (VERY DETAILED)
██████████████████████████████████████████████████████████

----------------------------------------------------------
WHY IS DATA CLEANING CRITICAL IN HEALTHCARE?
─────────────────────────────────────────────
1. Medical records are messy — free text, typos,
   lab instruments returning 0 for missing values.
2. A single wrong value in Cholesterol or Blood Pressure
   can shift model predictions, potentially causing
   incorrect diagnoses.
3. Missing data handled incorrectly can introduce bias.
4. Models fail silently on bad data — no error, just
   dangerously wrong predictions.
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  DATA CLEANING")
print("=" * 60)

# ── Step 4.1 : Check missing values column-wise ──────────
print("\n🔎  Step 4.1 — Missing value count per column:")
missing_counts = df.isnull().sum()
missing_pct    = (missing_counts / len(df)) * 100

missing_report = pd.DataFrame({
    'Missing Count'      : missing_counts,
    'Missing Percentage' : missing_pct.round(2)
})
print(missing_report)

# ── Step 4.2 : Interpret the missing report ──────────────
total_missing = missing_counts.sum()
if total_missing == 0:
    print("\n  ✅  No missing values found in any column.")
    print("      This dataset is already clean in terms of NaN values.")
    print("      However, we still perform the checks below because")
    print("      'missing' in medical data is sometimes encoded as 0.")
else:
    print(f"\n  ⚠️   Total missing cells: {total_missing}")

# ── Step 4.3 : Check for suspicious zero values ──────────
# In medical datasets, 0 sometimes means "not recorded",
# NOT a legitimate measurement.  We flag columns where 0
# is physiologically impossible.
print("\n🔎  Step 4.3 — Checking for suspicious zero values in"
      " continuous medical columns:")

suspicious_cols = {
    'RestingBP'   : "Resting Blood Pressure cannot be 0 (patient would be dead).",
    'Cholesterol' : "Serum Cholesterol of 0 is physiologically impossible."
}

for col, reason in suspicious_cols.items():
    if col in df.columns:
        zero_count = (df[col] == 0).sum()
        print(f"\n    Column : {col}")
        print(f"    Zeros  : {zero_count}")
        print(f"    Reason : {reason}")

        if zero_count > 0:
            print(f"    Action : Replacing 0s with column median "
                  f"({df[col].median():.1f})")
            # Replace 0 with median — median is preferred over mean
            # in medical data because it's resistant to outliers.
            df[col] = df[col].replace(0, df[col].median())
            print(f"    ✅  Zeros replaced.")
        else:
            print(f"    ✅  No suspicious zeros found.")

# ── Step 4.4 : Check for duplicate rows ──────────────────
print("\n🔎  Step 4.4 — Duplicate row check:")
dup_count = df.duplicated().sum()
print(f"    Duplicate rows found: {dup_count}")

if dup_count > 0:
    df = df.drop_duplicates()
    print(f"    ✅  {dup_count} duplicate row(s) removed.")
    print(f"    New shape: {df.shape}")
else:
    print("    ✅  No duplicate rows found.")

# ── Step 4.5 : Verify datatypes are sensible ─────────────
print("\n🔎  Step 4.5 — Datatype verification:")
print(df.dtypes)
print("\n    Categorical columns (object dtype) will be encoded in Section 6.")

# ── Step 4.6 : Reset index after cleaning ────────────────
df = df.reset_index(drop=True)
print(f"\n✅  Data cleaning complete.  Final dataset shape: {df.shape}")

"""██████████████████████████████████████████████████████████
 SECTION 5 ── EXPLORATORY DATA ANALYSIS (EDA)
██████████████████████████████████████████████████████████

----------------------------------------------------------
EDA lets us see the DATA before we model it.
Key questions we answer:
  1. What does the distribution of each feature look like?
  2. Are numeric features normally distributed or skewed?
  3. Which features correlate most with HeartDisease?
  4. Are categorical features balanced?
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  EXPLORATORY DATA ANALYSIS (EDA)")
print("=" * 60)

# ── Identify column types ─────────────────────────────────
numeric_cols     = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

# Remove target from numeric list for plotting
numeric_features = [c for c in numeric_cols if c != 'HeartDisease']

print(f"\n  Numeric columns    : {numeric_features}")
print(f"  Categorical columns: {categorical_cols}")

"""===========================================================
PLOT 5.1 — Distribution of Numeric Features
===========================================================
A histogram shows how values are spread across a range.
Skewed distributions may need log-transformation later.
"""

n_num = len(numeric_features)
fig, axes = plt.subplots(nrows=2,
                          ncols=(n_num + 1) // 2,
                          figsize=(16, 8))
axes = axes.flatten()   # flatten to 1-D for easy iteration

for i, col in enumerate(numeric_features):
    ax = axes[i]
    # KDE=True overlays a smooth density curve on the histogram
    ax.hist(df[col].dropna(), bins=30, color='steelblue',
            edgecolor='white', alpha=0.85)
    ax.set_title(f'Distribution of {col}', fontsize=11, fontweight='bold')
    ax.set_xlabel(col)
    ax.set_ylabel('Frequency')

# Hide any leftover empty subplot panels
for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

plt.suptitle('Figure 5.1 — Distribution of Numeric Features',
             fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('eda_numeric_distributions.png', dpi=150, bbox_inches='tight')
plt.show()
print("📊  Figure 5.1 saved as 'eda_numeric_distributions.png'")

"""===========================================================
PLOT 5.2 — Correlation Heatmap
===========================================================
Correlation tells us how strongly two numeric variables
move together.  Values range from -1 (perfect negative)
to +1 (perfect positive).  Values near 0 = no relationship.
We care most about the HeartDisease row/column.
"""

print("\n📊  Generating correlation heatmap ...")

# Select only numeric columns (including target) for correlation
corr_df = df[numeric_features + ['HeartDisease']]
corr_matrix = corr_df.corr()

plt.figure(figsize=(12, 9))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))  # hide upper triangle
sns.heatmap(
    corr_matrix,
    mask=mask,
    annot=True,          # show values inside cells
    fmt='.2f',           # 2 decimal places
    cmap='coolwarm',     # red = positive, blue = negative
    center=0,
    linewidths=0.5,
    linecolor='white',
    square=True,
    cbar_kws={'shrink': 0.75}
)
plt.title('Figure 5.2 — Correlation Heatmap\n'
          '(Lower triangle only to avoid redundancy)',
          fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('eda_correlation_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()
print("📊  Figure 5.2 saved as 'eda_correlation_heatmap.png'")

# Print the correlations with HeartDisease, sorted by abs value
print("\n  Feature correlations with HeartDisease (sorted):")
hd_corr = corr_matrix['HeartDisease'].drop('HeartDisease').abs().sort_values(
    ascending=False)
for feat, val in hd_corr.items():
    print(f"    {feat:<20} : {val:.3f}")

"""===========================================================
PLOT 5.3 — Count Plots for Categorical Variables
===========================================================
Count plots show the frequency of each category and how
they relate to the target (HeartDisease).
"""

if len(categorical_cols) > 0:
    n_cat = len(categorical_cols)
    fig, axes = plt.subplots(nrows=1, ncols=n_cat,
                              figsize=(5 * n_cat, 5))
    if n_cat == 1:
        axes = [axes]  # ensure iterable

    for i, col in enumerate(categorical_cols):
        ax = axes[i]
        # hue='HeartDisease' splits bars by target class
        sns.countplot(
            data=df,
            x=col,
            hue='HeartDisease',
            ax=ax,
            palette={0: 'steelblue', 1: 'salmon'}
        )
        ax.set_title(f'{col} vs HeartDisease',
                     fontsize=11, fontweight='bold')
        ax.set_xlabel(col)
        ax.set_ylabel('Count')
        ax.legend(title='HeartDisease',
                  labels=['0 (No)', '1 (Yes)'])
        # Rotate x labels if there are many categories
        ax.tick_params(axis='x', rotation=30)

    plt.suptitle('Figure 5.3 — Categorical Feature Count Plots '
                 '(by HeartDisease)',
                 fontsize=13, fontweight='bold', y=1.03)
    plt.tight_layout()
    plt.savefig('eda_categorical_countplots.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("📊  Figure 5.3 saved as 'eda_categorical_countplots.png'")
else:
    print("  ℹ️   No categorical columns found — skipping count plots.")

"""===========================================================
PLOT 5.4 — Boxplots: Numeric Features by Target
===========================================================
Boxplots reveal whether the distribution of a feature
differs between disease (1) and no-disease (0) groups.
Significant visual separation → the feature is informative.
"""

n_num = len(numeric_features)
fig, axes = plt.subplots(nrows=2,
                          ncols=(n_num + 1) // 2,
                          figsize=(16, 10))
axes = axes.flatten()

for i, col in enumerate(numeric_features):
    ax = axes[i]
    sns.boxplot(
        data=df,
        x='HeartDisease',
        y=col,
        palette={0: 'steelblue', 1: 'salmon'},
        ax=ax
    )
    ax.set_title(f'{col} by HeartDisease', fontsize=11, fontweight='bold')
    ax.set_xlabel('HeartDisease  (0=No, 1=Yes)')
    ax.set_ylabel(col)

for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

plt.suptitle('Figure 5.4 — Numeric Features vs Heart Disease (Boxplots)',
             fontsize=13, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('eda_boxplots.png', dpi=150, bbox_inches='tight')
plt.show()
print("📊  Figure 5.4 saved as 'eda_boxplots.png'")

print("\n✅  EDA complete.")

"""██████████████████████████████████████████████████████████
 SECTION 6 ── FEATURE ENGINEERING  (LABEL ENCODING)
██████████████████████████████████████████████████████████

----------------------------------------------------------
WHY DO WE NEED ENCODING?
─────────────────────────
Machine Learning algorithms work with NUMBERS.
Columns like Sex = 'M'/'F' or ChestPainType = 'ATA'
are strings — the algorithm cannot compute distances,
gradients, or splits on raw text.

Label Encoding assigns a unique integer to each category:
  Sex : M → 1,  F → 0

NOTE: Label Encoding implies ORDER (0 < 1 < 2 ...).
For features with no natural order, One-Hot Encoding is
theoretically better.  However, tree-based models (Random
Forest) handle Label-Encoded categoricals well, and for
this project Label Encoding keeps the data compact.
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  FEATURE ENGINEERING — LABEL ENCODING")
print("=" * 60)

# ── Step 6.1 : Identify categorical columns ───────────────
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print(f"\n  Categorical columns to encode: {categorical_cols}")

# ── Step 6.2 : Create and store a LabelEncoder per column ─
# We store each encoder in a dictionary so that during
# prediction we can reverse-transform if needed.
label_encoders = {}   # key = column name, value = fitted LabelEncoder

for col in categorical_cols:
    print(f"\n  Encoding column : '{col}'")

    # Inspect unique values BEFORE encoding
    unique_before = df[col].unique()
    print(f"    Unique values (before) : {sorted(unique_before)}")

    # Create a fresh LabelEncoder for this column
    le = LabelEncoder()

    # fit_transform:
    #   fit  → learn the mapping  e.g. {'ATA':0, 'ASY':1, 'NAP':2, 'TA':3}
    #   transform → apply mapping to the column
    df[col] = le.fit_transform(df[col])

    # Inspect unique values AFTER encoding
    unique_after = df[col].unique()
    print(f"    Unique values (after)  : {sorted(unique_after)}")

    # Print the explicit mapping for transparency
    mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print(f"    Mapping applied        : {mapping}")

    # Store the encoder for future use (inference time)
    label_encoders[col] = le

print(f"\n  Encoders stored for columns: {list(label_encoders.keys())}")

# ── Step 6.3 : Verify the DataFrame after encoding ────────
print("\n  DataFrame head after encoding:")
print(df.head())
print(f"\n  All dtypes after encoding:\n{df.dtypes}")
print("\n✅  Label encoding complete.")

"""██████████████████████████████████████████████████████████
 SECTION 7 ── FEATURE & TARGET SEPARATION
██████████████████████████████████████████████████████████

----------------------------------------------------------
We split the DataFrame into:
  X  →  feature matrix  (everything except the target)
  y  →  target vector   (HeartDisease column only)

This is a universal convention in Scikit-learn.
Every model's .fit(X, y) call expects this separation.
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  FEATURE & TARGET SEPARATION")
print("=" * 60)

# ── Define features (X) ───────────────────────────────────
# Drop the target column to get the feature matrix
X = df.drop(columns=['HeartDisease'])

# ── Define target (y) ─────────────────────────────────────
y = df['HeartDisease']

print(f"\n  Feature matrix X — shape : {X.shape}")
print(f"  Feature names            : {list(X.columns)}")
print(f"\n  Target vector y — shape  : {y.shape}")
print(f"  Target distribution      :\n{y.value_counts()}")

# ── Sanity check: rows must match ─────────────────────────
assert X.shape[0] == y.shape[0], \
    "ERROR: X and y must have the same number of rows!"
print("\n✅  Shapes are consistent — X and y ready.")

"""██████████████████████████████████████████████████████████
 SECTION 8 ── TRAIN-TEST SPLIT
██████████████████████████████████████████████████████████

----------------------------------------------------------
WHY DO WE SPLIT THE DATA?
──────────────────────────
If we train and evaluate on the SAME data, the model
memorises the training examples instead of learning
patterns.  This is called OVERFITTING.

By holding out 20% of data as a "test set", we simulate
how the model would perform on UNSEEN future patients.
This is the gold standard evaluation in ML.

Stratify ensures the class ratio is preserved in both
splits — crucial in healthcare so neither split is
accidentally all one class.
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  TRAIN-TEST SPLIT  (80 % train  /  20 % test)")
print("=" * 60)

X_train, X_test, y_train, y_test = train_test_split(
    X,                 # feature matrix
    y,                 # target vector
    test_size=0.20,    # 20 % reserved for testing
    random_state=42,   # seed for reproducibility
    stratify=y         # maintain class proportions
)

print(f"\n  Training set   X_train : {X_train.shape}")
print(f"  Test set       X_test  : {X_test.shape}")
print(f"  Training labels y_train: {y_train.shape}  "
      f"| Class 0: {(y_train==0).sum()}  Class 1: {(y_train==1).sum()}")
print(f"  Test labels    y_test  : {y_test.shape}   "
      f"| Class 0: {(y_test==0).sum()}  Class 1: {(y_test==1).sum()}")

# Verify stratification
train_ratio = y_train.mean()
test_ratio  = y_test.mean()
print(f"\n  Positive class ratio — Train: {train_ratio:.3f}  "
      f"Test: {test_ratio:.3f}")
print("  ✅  Stratification maintained (ratios should be similar).")

"""██████████████████████████████████████████████████████████
 SECTION 9 ── FEATURE SCALING
██████████████████████████████████████████████████████████

----------------------------------------------------------
WHY IS SCALING REQUIRED?
─────────────────────────
Features like Age range from 28–77 while
Cholesterol ranges from 0–600.
Algorithms that use distance (SVM, KNN, Logistic
Regression) will incorrectly give more WEIGHT to
features with larger numeric ranges.

StandardScaler transforms each feature so that:
  new_value = (original_value - mean) / std_deviation
After scaling: mean = 0,  std = 1 for each feature.

IMPORTANT RULE:
  - Fit  (learn mean/std) ONLY on TRAINING data.
  - Transform BOTH train and test with those same stats.
  - Never fit on test data — that leaks future information!
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  FEATURE SCALING  (StandardScaler)")
print("=" * 60)

# ── Instantiate the scaler ────────────────────────────────
scaler = StandardScaler()

# ── Peek at one column BEFORE scaling ────────────────────
example_col = 'Age'
print(f"\n  Example — Column '{example_col}' BEFORE scaling:")
print(f"    Mean : {X_train[example_col].mean():.2f}")
print(f"    Std  : {X_train[example_col].std():.2f}")
print(f"    Min  : {X_train[example_col].min():.2f}")
print(f"    Max  : {X_train[example_col].max():.2f}")

# ── Fit on training data, transform both sets ─────────────
# fit_transform on train: learns the statistics AND applies them
X_train_scaled = scaler.fit_transform(X_train)

# transform on test: uses the SAME mean/std learned from train
X_test_scaled  = scaler.transform(X_test)

# Convert back to DataFrames so column names are preserved
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X.columns)
X_test_scaled  = pd.DataFrame(X_test_scaled,  columns=X.columns)

# ── Peek at the same column AFTER scaling ─────────────────
print(f"\n  Example — Column '{example_col}' AFTER scaling:")
print(f"    Mean : {X_train_scaled[example_col].mean():.4f}  (≈ 0)")
print(f"    Std  : {X_train_scaled[example_col].std():.4f}   (≈ 1)")
print(f"    Min  : {X_train_scaled[example_col].min():.4f}")
print(f"    Max  : {X_train_scaled[example_col].max():.4f}")

print("\n✅  Scaling complete.")
print(f"    X_train_scaled shape : {X_train_scaled.shape}")
print(f"    X_test_scaled  shape : {X_test_scaled.shape}")

"""██████████████████████████████████████████████████████████
 SECTION 10 ── MODEL TRAINING
██████████████████████████████████████████████████████████

----------------------------------------------------------
We train THREE models to compare different approaches:

 1. Logistic Regression  — Linear probabilistic baseline.
    Fast, interpretable, good for linearly-separable data.

 2. Random Forest        — Ensemble of 100 decision trees.
    Robust to noise, handles non-linear relationships,
    provides feature importance scores.

 3. Support Vector Machine (SVM) — Finds the optimal
    hyperplane that maximises the margin between classes.
    Excellent on small-to-medium datasets.

All models are trained on scaled training data.
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  MODEL TRAINING")
print("=" * 60)

# ── Helper function: train + predict ──────────────────────
def train_model(model, X_tr, y_tr, X_te, model_name):
    """
    Train a model and return predictions on the test set.

    Parameters
    ----------
    model      : instantiated (but unfitted) sklearn estimator
    X_tr       : scaled training features
    y_tr       : training labels
    X_te       : scaled test features
    model_name : string label for printing

    Returns
    -------
    y_pred     : numpy array of predictions on X_te
    """
    print(f"\n  ▶  Training  {model_name} ...")
    model.fit(X_tr, y_tr)           # learn from training data
    y_pred = model.predict(X_te)    # generate predictions on test data
    print(f"     {model_name} — training complete.")
    return y_pred

"""── 10.1  Logistic Regression ─────────────────────────────
max_iter=1000 ensures convergence on this dataset size.
class_weight='balanced' adjusts weights inversely
proportional to class frequency — helpful for imbalance.
"""

lr_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    random_state=42
)
lr_preds = train_model(lr_model, X_train_scaled, y_train,
                        X_test_scaled, "Logistic Regression")

"""── 10.2  Random Forest Classifier ───────────────────────
n_estimators=100 → 100 independent decision trees.
Each tree is trained on a bootstrap sample of the data
(sampling with replacement).  Final prediction is the
majority vote across all 100 trees — this averaging
REDUCES variance compared to a single tree.
"""

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,          # trees grow until leaves are pure
    class_weight='balanced',
    random_state=42,
    n_jobs=-1                # use all available CPU cores
)
rf_preds = train_model(rf_model, X_train_scaled, y_train,
                        X_test_scaled, "Random Forest")

"""── 10.3  Support Vector Machine ─────────────────────────
kernel='rbf' (Radial Basis Function) maps data into a
higher-dimensional space where it may be linearly separable.
C=1.0 is the regularisation parameter:
  - large C  → tries to classify all training points correctly
              (risk of overfitting)
  - small C  → allows some misclassifications for a wider margin
              (more generalisation)
probability=True allows predict_proba() for ROC curves later.
"""

svm_model = SVC(
    kernel='rbf',
    C=1.0,
    gamma='scale',
    class_weight='balanced',
    probability=True,
    random_state=42
)
svm_preds = train_model(svm_model, X_train_scaled, y_train,
                         X_test_scaled, "SVM (RBF Kernel)")

print("\n✅  All three models trained and predictions generated.")

"""██████████████████████████████████████████████████████████
 SECTION 11 ── MODEL EVALUATION  (VERY IMPORTANT)
██████████████████████████████████████████████████████████

----------------------------------------------------------
METRIC GLOSSARY FOR HEALTHCARE ML
───────────────────────────────────
True Positive (TP) : Predicted disease,  actually has disease.
True Negative (TN) : Predicted no disease, actually none.
False Positive (FP): Predicted disease,  actually NONE  ← "False alarm"
False Negative (FN): Predicted NO disease, ACTUALLY HAS ← "Missed case"

Accuracy  = (TP+TN)/(TP+TN+FP+FN)
            → % of all predictions that are correct.
            → Misleading when classes are imbalanced.

Precision = TP/(TP+FP)
            → Of those we flagged as positive, how many truly are?
            → High precision = fewer false alarms.

Recall    = TP/(TP+FN)
            → Of all real positive cases, how many did we catch?
            → ⭐ MOST IMPORTANT in healthcare — missing a real
              heart disease case is far worse than a false alarm.

F1-Score  = 2 × (Precision × Recall) / (Precision + Recall)
            → Harmonic mean.  Good when precision & recall matter.

Confusion Matrix:
  [[TN  FP]
   [FN  TP]]
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  MODEL EVALUATION")
print("=" * 60)

# Pack models and their predictions for loop iteration
models_info = [
    ("Logistic Regression", lr_model,  lr_preds),
    ("Random Forest",        rf_model,  rf_preds),
    ("SVM (RBF Kernel)",     svm_model, svm_preds)
]

# Storage dict for comparison table in Section 12
results_storage = {}

for model_name, model_obj, y_pred in models_info:
    print(f"\n{'─'*55}")
    print(f"  📌  Model : {model_name}")
    print(f"{'─'*55}")

    # ── Compute metrics ───────────────────────────────────
    acc  = accuracy_score (y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec  = recall_score   (y_test, y_pred, zero_division=0)
    f1   = f1_score       (y_test, y_pred, zero_division=0)
    cm   = confusion_matrix(y_test, y_pred)

    # ── Print metrics ─────────────────────────────────────
    print(f"\n  Accuracy  : {acc:.4f}  ({acc*100:.2f}%)")
    print(f"  Precision : {prec:.4f}  ({prec*100:.2f}%)")
    print(f"  Recall    : {rec:.4f}  ({rec*100:.2f}%)")
    print(f"  F1-Score  : {f1:.4f}  ({f1*100:.2f}%)")

    # ── Full classification report ────────────────────────
    print(f"\n  Full Classification Report:")
    print(classification_report(y_test, y_pred,
                                 target_names=['No Disease', 'Disease']))

    # ── Confusion matrix plot ─────────────────────────────
    plt.figure(figsize=(5, 4))
    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        cmap='Blues',
        xticklabels=['Pred: No', 'Pred: Yes'],
        yticklabels=['True: No', 'True: Yes'],
        linewidths=1,
        linecolor='white'
    )
    plt.title(f'Confusion Matrix — {model_name}',
              fontsize=12, fontweight='bold')
    plt.ylabel('Actual Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    fname = f"cm_{model_name.replace(' ', '_').replace('(', '').replace(')', '')}.png"
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"  📊  Confusion matrix saved as '{fname}'")

    # ── Interpret the confusion matrix ───────────────────
    tn, fp, fn, tp = cm.ravel()
    print(f"\n  Confusion Matrix Breakdown:")
    print(f"    True Negatives  (TN): {tn}  "
          "→ Correctly predicted NO disease")
    print(f"    False Positives (FP): {fp}  "
          "→ Predicted disease, actually NONE (false alarm)")
    print(f"    False Negatives (FN): {fn}  "
          "→ ⚠️  Missed disease cases  ← we want this LOWEST")
    print(f"    True Positives  (TP): {tp}  "
          "→ Correctly predicted disease")

    # ── Store for comparison ──────────────────────────────
    results_storage[model_name] = {
        'Accuracy'  : round(acc,  4),
        'Precision' : round(prec, 4),
        'Recall'    : round(rec,  4),
        'F1-Score'  : round(f1,   4),
        'FN'        : fn
    }

print("\n✅  Evaluation of all models complete.")

"""██████████████████████████████████████████████████████████
 SECTION 12 ── MODEL COMPARISON
██████████████████████████████████████████████████████████

----------------------------------------------------------
We assemble a side-by-side comparison table to determine
the best model for deployment.

In healthcare, RECALL is the primary selection criterion
because:
  Low Recall → many False Negatives → patients with heart
  disease go undiagnosed → life-threatening consequences.

A missed positive is ALWAYS more dangerous than a false
alarm in a screening scenario.
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  MODEL COMPARISON TABLE")
print("=" * 60)

# Build comparison DataFrame
comparison_df = pd.DataFrame(results_storage).T
comparison_df.index.name = 'Model'
comparison_df = comparison_df.reset_index()

print("\n", comparison_df.to_string(index=False))

# ── Identify best model by Recall ────────────────────────
best_recall_idx   = comparison_df['Recall'].astype(float).idxmax()
best_model_name   = comparison_df.loc[best_recall_idx, 'Model']
best_recall_val   = comparison_df.loc[best_recall_idx, 'Recall']

# Also identify best by F1 (tie-breaker)
best_f1_idx       = comparison_df['F1-Score'].astype(float).idxmax()
best_f1_name      = comparison_df.loc[best_f1_idx, 'Model']
best_f1_val       = comparison_df.loc[best_f1_idx, 'F1-Score']

print(f"\n  🏆  Best Recall   → {best_model_name}  "
      f"(Recall = {best_recall_val})")
print(f"  🏆  Best F1-Score → {best_f1_name}  "
      f"(F1 = {best_f1_val})")

print("""
  ──────────────────────────────────────────────────────
  WHY RECALL MATTERS MOST IN HEART DISEASE DETECTION
  ──────────────────────────────────────────────────────
  In clinical screening:
    • A False Negative means a patient who HAS heart disease
      is told they are healthy.  They leave without treatment.
      This can result in a fatal heart attack.

    • A False Positive means a patient is flagged for further
      tests — an inconvenience, but NOT life-threatening.

  Therefore, we PRIORITISE RECALL (minimise False Negatives)
  even at the cost of slightly lower Precision.

  The model with the HIGHEST RECALL should be selected
  for production deployment unless another model achieves
  equal recall with substantially better precision.
  ──────────────────────────────────────────────────────
""")

# ── Visual bar chart comparison ───────────────────────────
metrics_to_plot = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
x = np.arange(len(metrics_to_plot))
bar_width = 0.25
colours = ['steelblue', 'seagreen', 'salmon']

fig, ax = plt.subplots(figsize=(12, 6))

for i, (_, row) in enumerate(comparison_df.iterrows()):
    values = [float(row[m]) for m in metrics_to_plot]
    bars   = ax.bar(x + i * bar_width, values,
                     width=bar_width,
                     color=colours[i],
                     label=row['Model'],
                     alpha=0.85,
                     edgecolor='white')
    # Annotate bar tops
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.005,
                f"{bar.get_height():.3f}",
                ha='center', va='bottom', fontsize=8)

ax.set_xticks(x + bar_width)
ax.set_xticklabels(metrics_to_plot, fontsize=11)
ax.set_ylim(0, 1.1)
ax.set_ylabel('Score', fontsize=11)
ax.set_title('Figure 12 — Model Comparison Across Metrics',
             fontsize=13, fontweight='bold')
ax.legend(fontsize=10)
ax.axhline(y=0.9, color='grey', linestyle='--', linewidth=0.8,
            label='0.9 reference')
plt.tight_layout()
plt.savefig('model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("📊  Figure 12 saved as 'model_comparison.png'")

"""██████████████████████████████████████████████████████████
 SECTION 13 ── FEATURE IMPORTANCE (RANDOM FOREST)
██████████████████████████████████████████████████████████

----------------------------------------------------------
Random Forest internally records how much each feature
REDUCED IMPURITY (Gini impurity) across all splits
of all 100 trees.

A high importance score means that feature was heavily
relied upon to make splitting decisions → it is a strong
predictor of heart disease.

Clinical value: High-importance features should be
prioritised in patient screening questionnaires.
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  FEATURE IMPORTANCE (Random Forest)")
print("=" * 60)

# Extract feature importances from the trained RF model
importances   = rf_model.feature_importances_
feature_names = list(X.columns)

# Create a DataFrame for easy sorting and plotting
importance_df = pd.DataFrame({
    'Feature'   : feature_names,
    'Importance': importances
})

# Sort descending so most important features appear first
importance_df = importance_df.sort_values(
    by='Importance', ascending=False
).reset_index(drop=True)

print("\n  Feature Importance Ranking:")
for rank, row in importance_df.iterrows():
    bar = '█' * int(row['Importance'] * 100)
    print(f"  {rank+1:>2}. {row['Feature']:<22} {row['Importance']:.4f}  {bar}")

# ── Plot feature importance ────────────────────────────────
plt.figure(figsize=(10, 6))
colours_importance = plt.cm.RdYlGn(
    np.linspace(0.3, 0.9, len(importance_df))
)[::-1]  # green → high, red → low

bars = plt.barh(
    importance_df['Feature'][::-1],   # reverse for top→bottom display
    importance_df['Importance'][::-1],
    color=colours_importance,
    edgecolor='white',
    height=0.6
)

# Annotate bars with exact values
for bar in bars:
    plt.text(
        bar.get_width() + 0.002,
        bar.get_y() + bar.get_height() / 2,
        f"{bar.get_width():.4f}",
        va='center', ha='left', fontsize=9
    )

plt.xlabel('Importance Score (Mean Decrease in Gini Impurity)', fontsize=11)
plt.ylabel('Feature', fontsize=11)
plt.title('Figure 13 — Feature Importance — Random Forest Classifier',
          fontsize=13, fontweight='bold')
plt.xlim(0, importance_df['Importance'].max() * 1.2)
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()
print("📊  Figure 13 saved as 'feature_importance.png'")

# ── Interpret top 3 features ──────────────────────────────
print("\n  Clinical Interpretation of Top 3 Features:")
for i in range(min(3, len(importance_df))):
    feat  = importance_df.loc[i, 'Feature']
    score = importance_df.loc[i, 'Importance']
    print(f"\n  #{i+1}  {feat}  (importance = {score:.4f})")
    interpretations = {
        'Oldpeak'       : "ST depression induced by exercise — a key ECG marker "
                          "of myocardial ischaemia.",
        'ST_Slope'      : "Slope of peak-exercise ST segment — flat/down slope "
                          "strongly correlates with disease.",
        'MaxHR'         : "Lower maximum HR during exercise suggests reduced "
                          "cardiac reserve.",
        'ChestPainType' : "Asymptomatic chest pain is paradoxically associated "
                          "with higher heart disease risk.",
        'Age'           : "Older age increases cumulative cardiovascular risk.",
        'Cholesterol'   : "Elevated LDL contributes to arterial plaque buildup.",
        'Sex'           : "Males have higher prevalence in this dataset.",
        'ExerciseAngina': "Angina during exercise directly indicates ischaemia.",
        'FastingBS'     : "Fasting blood sugar >120 mg/dl → diabetic risk factor.",
        'RestingBP'     : "Hypertension is a primary risk factor.",
        'RestingECG'    : "Abnormal resting ECG patterns signal existing damage."
    }
    desc = interpretations.get(feat, "Important predictor identified by the model.")
    print(f"     → {desc}")

"""██████████████████████████████████████████████████████████
 SECTION 14 ── SAVE MODEL & SCALER
██████████████████████████████████████████████████████████

----------------------------------------------------------
WHY SAVE THE MODEL?
────────────────────
Training is time-consuming.  Once we've found the best
model, we serialise it to disk so that:
  1. We can reload it in a Flask / FastAPI backend without
     retraining (save compute and time).
  2. We can version-control models alongside the codebase.
  3. We can deploy to production servers or Docker containers.

We also save the SCALER because at inference time:
  new_patient_data → MUST be scaled with the SAME scaler
  that was used during training.
  A different scaler will produce different numeric values
  and corrupt every prediction.
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  SAVE MODEL & SCALER")
print("=" * 60)

# ── Determine which model to save ─────────────────────────
# We save Random Forest as it generally achieves the best
# balance of recall and F1 in this project.  Change
# 'best_model_to_save' if your evaluation shows otherwise.
best_model_to_save = rf_model
best_model_label   = "Random Forest"

# ── Create output directory ───────────────────────────────
save_dir = 'lifescan_models'
os.makedirs(save_dir, exist_ok=True)

# ── Save the trained model ────────────────────────────────
model_path  = os.path.join(save_dir, 'heart_disease_model.pkl')
joblib.dump(best_model_to_save, model_path)
print(f"\n  ✅  Model  saved → {model_path}")

# ── Save the scaler ───────────────────────────────────────
scaler_path = os.path.join(save_dir, 'feature_scaler.pkl')
joblib.dump(scaler, scaler_path)
print(f"  ✅  Scaler saved → {scaler_path}")

# ── Save label encoders ───────────────────────────────────
encoders_path = os.path.join(save_dir, 'label_encoders.pkl')
joblib.dump(label_encoders, encoders_path)
print(f"  ✅  Label encoders saved → {encoders_path}")

# ── Verify saved files ────────────────────────────────────
print("\n  Files in save directory:")
for f in os.listdir(save_dir):
    fpath = os.path.join(save_dir, f)
    fsize = os.path.getsize(fpath)
    print(f"    {f}  ({fsize} bytes)")

# ── Test: reload and predict to confirm integrity ─────────
print("\n  🔄  Reload test — loading saved model ...")
loaded_model  = joblib.load(model_path)
loaded_scaler = joblib.load(scaler_path)

# Quick sanity check on test set
reload_preds = loaded_model.predict(
    loaded_scaler.transform(X_test)
)
reload_acc = accuracy_score(y_test, reload_preds)
print(f"     Reloaded model accuracy on test set: "
      f"{reload_acc*100:.2f}%")
print("  ✅  Model reloaded successfully — predictions match.")

"""██████████████████████████████████████████████████████████
 SECTION 15 ── CUSTOM PREDICTION FUNCTION
██████████████████████████████████████████████████████████

----------------------------------------------------------
This function is the INFERENCE LAYER of the system.
In a production environment (Flask API, Streamlit app,
MERN backend), you would call this function with patient
data received from the frontend and return the risk label.

Pipeline inside the function:
  1. Accept raw patient data as a dictionary.
  2. Convert to a single-row DataFrame (same column order
     as training data).
  3. Encode categorical values using saved encoders.
  4. Scale using the saved StandardScaler.
  5. Predict using the saved model.
  6. Return the label AND the probability for display.
----------------------------------------------------------
"""

print("\n" + "=" * 60)
print("  CUSTOM PREDICTION FUNCTION")
print("=" * 60)

def predict_heart_disease(patient_data: dict,
                           model,
                           scaler,
                           encoders: dict,
                           feature_order: list) -> dict:
    """
    Predict heart disease risk for a single patient.

    Parameters
    ----------
    patient_data  : dict — raw patient values (strings for
                    categorical features, numbers for numeric).
    model         : trained sklearn classifier.
    scaler        : fitted StandardScaler.
    encoders      : dict mapping column name → LabelEncoder.
    feature_order : list of feature names in the exact order
                    used during training.

    Returns
    -------
    dict with keys:
        'prediction'  : int  (0 or 1)
        'label'       : str  ('No Heart Disease' or 'Heart Disease')
        'probability' : float (confidence of the positive class)
        'risk_level'  : str  ('Low', 'Moderate', 'High')
    """

    # ── Step 1: Create a single-row DataFrame ─────────────
    # This ensures the input has named columns, making it
    # immune to column-order mistakes.
    input_df = pd.DataFrame([patient_data])

    # ── Step 2: Reorder columns to match training order ───
    # The model was trained with a specific column order.
    # If the order changes, feature X[3] during prediction
    # might correspond to feature X[2] during training.
    input_df = input_df[feature_order]

    # ── Step 3: Encode categorical columns ────────────────
    for col, le in encoders.items():
        if col in input_df.columns:
            raw_val     = input_df[col].values[0]
            encoded_val = le.transform([raw_val])[0]
            input_df[col] = encoded_val

    # ── Step 4: Apply StandardScaler ──────────────────────
    input_scaled = scaler.transform(input_df)

    # ── Step 5: Predict ───────────────────────────────────
    prediction  = model.predict(input_scaled)[0]

    # predict_proba returns [[prob_class0, prob_class1]]
    probability = model.predict_proba(input_scaled)[0][1]

    # ── Step 6: Interpret result ──────────────────────────
    label = "Heart Disease Detected" if prediction == 1 \
            else "No Heart Disease"

    if probability < 0.35:
        risk_level = "Low"
    elif probability < 0.65:
        risk_level = "Moderate"
    else:
        risk_level = "High"

    return {
        'prediction'  : int(prediction),
        'label'       : label,
        'probability' : round(float(probability), 4),
        'risk_level'  : risk_level
    }

# ── Retrieve the feature order used during training ───────
feature_order = list(X.columns)

# ── Demo Prediction 1 : High-risk patient ─────────────────
print("\n  ─── Demo Prediction 1 : HIGH-RISK profile ───────────")
high_risk_patient = {
    'Age'           : 65,
    'Sex'           : 'M',
    'ChestPainType' : 'ASY',   # ASY = Asymptomatic → high risk flag
    'RestingBP'     : 145,
    'Cholesterol'   : 289,
    'FastingBS'     : 1,       # >120 mg/dl → diabetic indicator
    'RestingECG'    : 'LVH',   # Left Ventricular Hypertrophy
    'MaxHR'         : 110,
    'ExerciseAngina': 'Y',
    'Oldpeak'       : 2.5,
    'ST_Slope'      : 'Flat'
}

result_1 = predict_heart_disease(
    patient_data  = high_risk_patient,
    model         = loaded_model,
    scaler        = loaded_scaler,
    encoders      = label_encoders,
    feature_order = feature_order
)

print(f"\n  Patient Input  : {high_risk_patient}")
print(f"\n  ── Prediction Result ──")
print(f"     Prediction   : {result_1['prediction']}")
print(f"     Label        : {result_1['label']}")
print(f"     Probability  : {result_1['probability']*100:.1f}%")
print(f"     Risk Level   : {result_1['risk_level']}")

# ── Demo Prediction 2 : Low-risk patient ──────────────────
print("\n  ─── Demo Prediction 2 : LOW-RISK profile ────────────")
low_risk_patient = {
    'Age'           : 40,
    'Sex'           : 'F',
    'ChestPainType' : 'ATA',   # ATA = Atypical Angina → lower risk
    'RestingBP'     : 118,
    'Cholesterol'   : 195,
    'FastingBS'     : 0,
    'RestingECG'    : 'Normal',
    'MaxHR'         : 165,
    'ExerciseAngina': 'N',
    'Oldpeak'       : 0.0,
    'ST_Slope'      : 'Up'
}

result_2 = predict_heart_disease(
    patient_data  = low_risk_patient,
    model         = loaded_model,
    scaler        = loaded_scaler,
    encoders      = label_encoders,
    feature_order = feature_order
)

print(f"\n  Patient Input  : {low_risk_patient}")
print(f"\n  ── Prediction Result ──")
print(f"     Prediction   : {result_2['prediction']}")
print(f"     Label        : {result_2['label']}")
print(f"     Probability  : {result_2['probability']*100:.1f}%")
print(f"     Risk Level   : {result_2['risk_level']}")

# ── Demo Prediction 3 : Borderline patient ────────────────
print("\n  ─── Demo Prediction 3 : MODERATE-RISK profile ───────")
moderate_risk_patient = {
    'Age'           : 54,
    'Sex'           : 'M',
    'ChestPainType' : 'NAP',
    'RestingBP'     : 130,
    'Cholesterol'   : 245,
    'FastingBS'     : 0,
    'RestingECG'    : 'ST',
    'MaxHR'         : 142,
    'ExerciseAngina': 'N',
    'Oldpeak'       : 1.1,
    'ST_Slope'      : 'Flat'
}

result_3 = predict_heart_disease(
    patient_data  = moderate_risk_patient,
    model         = loaded_model,
    scaler        = loaded_scaler,
    encoders      = label_encoders,
    feature_order = feature_order
)

print(f"\n  Patient Input  : {moderate_risk_patient}")
print(f"\n  ── Prediction Result ──")
print(f"     Prediction   : {result_3['prediction']}")
print(f"     Label        : {result_3['label']}")
print(f"     Probability  : {result_3['probability']*100:.1f}%")
print(f"     Risk Level   : {result_3['risk_level']}")

"""██████████████████████████████████████████████████████████
 SECTION 16 ── FINAL SUMMARY & PIPELINE OVERVIEW
██████████████████████████████████████████████████████████
"""

print("\n" + "=" * 60)
print("  LIFESCAN AI SYSTEM — PIPELINE COMPLETE")
print("=" * 60)

print("""
  ┌──────────────────────────────────────────────────────┐
  │             PIPELINE SUMMARY                         │
  ├─────────────────────────────────────────────────────-│
  │  Step  1  │ Libraries imported                       │
  │  Step  2  │ Dataset loaded   (heart.csv)             │
  │  Step  3  │ Data understood  (.info / .describe)     │
  │  Step  4  │ Data cleaned     (zeros, duplicates)     │
  │  Step  5  │ EDA completed    (4 visualisations)      │
  │  Step  6  │ Features encoded (LabelEncoder)          │
  │  Step  7  │ X / y separated                          │
  │  Step  8  │ 80/20 train-test split (stratified)      │
  │  Step  9  │ StandardScaler applied                   │
  │  Step 10  │ 3 models trained (LR, RF, SVM)           │
  │  Step 11  │ All models evaluated (Acc/Prec/Rec/F1)   │
  │  Step 12  │ Models compared — best selected          │
  │  Step 13  │ Feature importance plotted (RF)          │
  │  Step 14  │ Model + Scaler + Encoders saved          │
  │  Step 15  │ Prediction function demonstrated         │
  └──────────────────────────────────────────────────────┘
""")

print("  Files produced during this session:")
print("    eda_numeric_distributions.png")
print("    eda_correlation_heatmap.png")
print("    eda_categorical_countplots.png")
print("    eda_boxplots.png")
print("    cm_Logistic_Regression.png")
print("    cm_Random_Forest.png")
print("    cm_SVM_RBF_Kernel.png")
print("    model_comparison.png")
print("    feature_importance.png")
print("    lifescan_models/heart_disease_model.pkl")
print("    lifescan_models/feature_scaler.pkl")
print("    lifescan_models/label_encoders.pkl")

print("""
  ── NEXT STEPS FOR PRODUCTION ──────────────────────────
  1. Wrap predict_heart_disease() in a Flask/FastAPI endpoint.
  2. Accept JSON input from your MERN frontend.
  3. Return the prediction dict as a JSON response.
  4. Add authentication, logging, and input validation.
  5. Consider SHAP values for per-patient explainability.
  6. Retrain monthly as new patient data accumulates.
  ───────────────────────────────────────────────────────

  LifeScan AI System — Built for healthcare, designed
  for reliability, explained for trust.
""")
print("=" * 60)
print("  ✅  END OF NOTEBOOK  — LifeScan AI System")
print("=" * 60)